-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- Table: workdays
create table if not exists public.workdays (
    id uuid primary key default uuid_generate_v4(),
    user_id text not null,
    date text not null,
    start_time bigint,
    end_time bigint,
    status text not null,
    last_new_job_prompt_time bigint,
    last_job_completion_prompt_time bigint,
    current_job_id text,
    start_location_latitude double precision,
    start_location_longitude double precision,
    start_location_timestamp bigint,
    end_location_latitude double precision,
    end_location_longitude double precision,
    end_location_timestamp bigint,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Table: jobs
create table if not exists public.jobs (
    id uuid primary key default uuid_generate_v4(),
    workday_id uuid references public.workdays(id) on delete cascade,
    description text,
    start_time bigint,
    end_time bigint,
    summary text,
    ai_summary text,
    status text,
    start_location_latitude double precision,
    start_location_longitude double precision,
    start_location_timestamp bigint,
    start_location_accuracy double precision,
    end_location_latitude double precision,
    end_location_longitude double precision,
    end_location_timestamp bigint,
    created_at timestamptz default now()
);

-- Table: pause_intervals
create table if not exists public.pause_intervals (
    id uuid primary key default uuid_generate_v4(),
    workday_id uuid references public.workdays(id) on delete cascade,
    start_time bigint,
    end_time bigint,
    start_location_latitude double precision,
    start_location_longitude double precision,
    start_location_timestamp bigint,
    start_location_accuracy double precision,
    end_location_latitude double precision,
    end_location_longitude double precision,
    end_location_timestamp bigint,
    created_at timestamptz default now()
);

-- Table: events
create table if not exists public.events (
    id uuid primary key default uuid_generate_v4(),
    workday_id uuid references public.workdays(id) on delete cascade,
    type text not null,
    timestamp bigint,
    job_id text,
    details text,
    location_latitude double precision,
    location_longitude double precision,
    location_timestamp bigint,
    location_accuracy double precision,
    created_at timestamptz default now()
);

-- Table: locations
create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    workday_id uuid references public.workdays(id) on delete cascade,
    latitude double precision not null,
    longitude double precision not null,
    timestamp bigint,
    accuracy double precision,
    created_at timestamptz default now()
);

-- Indexes for better performance
create index if not exists idx_workdays_user_id on public.workdays(user_id);
create index if not exists idx_workdays_date on public.workdays(date);
create index if not exists idx_jobs_workday_id on public.jobs(workday_id);
create index if not exists idx_pause_intervals_workday_id on public.pause_intervals(workday_id);
create index if not exists idx_events_workday_id on public.events(workday_id);
create index if not exists idx_locations_workday_id on public.locations(workday_id);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.workdays enable row level security;
alter table public.jobs enable row level security;
alter table public.pause_intervals enable row level security;
alter table public.events enable row level security;
alter table public.locations enable row level security;

-- Create policies (Open access for now as per typical dev setup, adjust for production)
create policy "Enable read access for all users" on public.workdays for select using (true);
create policy "Enable insert access for all users" on public.workdays for insert with check (true);
create policy "Enable update access for all users" on public.workdays for update using (true);

create policy "Enable read access for all users" on public.jobs for select using (true);
create policy "Enable insert access for all users" on public.jobs for insert with check (true);
create policy "Enable update access for all users" on public.jobs for update using (true);

create policy "Enable read access for all users" on public.pause_intervals for select using (true);
create policy "Enable insert access for all users" on public.pause_intervals for insert with check (true);
create policy "Enable update access for all users" on public.pause_intervals for update using (true);

create policy "Enable read access for all users" on public.events for select using (true);
create policy "Enable insert access for all users" on public.events for insert with check (true);
create policy "Enable update access for all users" on public.events for update using (true);

create policy "Enable read access for all users" on public.locations for select using (true);
create policy "Enable insert access for all users" on public.locations for insert with check (true);
